// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	rayv1 "github.com/ray-project/kuberay/ray-operator/apis/ray/v1"
	applyconfigurationrayv1 "github.com/ray-project/kuberay/ray-operator/pkg/client/applyconfiguration/ray/v1"
	scheme "github.com/ray-project/kuberay/ray-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// FederatedRayClustersGetter has a method to return a FederatedRayClusterInterface.
// A group's client should implement this interface.
type FederatedRayClustersGetter interface {
	FederatedRayClusters(namespace string) FederatedRayClusterInterface
}

// FederatedRayClusterInterface has methods to work with FederatedRayCluster resources.
type FederatedRayClusterInterface interface {
	Create(ctx context.Context, federatedRayCluster *rayv1.FederatedRayCluster, opts metav1.CreateOptions) (*rayv1.FederatedRayCluster, error)
	Update(ctx context.Context, federatedRayCluster *rayv1.FederatedRayCluster, opts metav1.UpdateOptions) (*rayv1.FederatedRayCluster, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, federatedRayCluster *rayv1.FederatedRayCluster, opts metav1.UpdateOptions) (*rayv1.FederatedRayCluster, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*rayv1.FederatedRayCluster, error)
	List(ctx context.Context, opts metav1.ListOptions) (*rayv1.FederatedRayClusterList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *rayv1.FederatedRayCluster, err error)
	Apply(ctx context.Context, federatedRayCluster *applyconfigurationrayv1.FederatedRayClusterApplyConfiguration, opts metav1.ApplyOptions) (result *rayv1.FederatedRayCluster, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, federatedRayCluster *applyconfigurationrayv1.FederatedRayClusterApplyConfiguration, opts metav1.ApplyOptions) (result *rayv1.FederatedRayCluster, err error)
	FederatedRayClusterExpansion
}

// federatedRayClusters implements FederatedRayClusterInterface
type federatedRayClusters struct {
	*gentype.ClientWithListAndApply[*rayv1.FederatedRayCluster, *rayv1.FederatedRayClusterList, *applyconfigurationrayv1.FederatedRayClusterApplyConfiguration]
}

// newFederatedRayClusters returns a FederatedRayClusters
func newFederatedRayClusters(c *RayV1Client, namespace string) *federatedRayClusters {
	return &federatedRayClusters{
		gentype.NewClientWithListAndApply[*rayv1.FederatedRayCluster, *rayv1.FederatedRayClusterList, *applyconfigurationrayv1.FederatedRayClusterApplyConfiguration](
			"federatedrayclusters",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *rayv1.FederatedRayCluster { return &rayv1.FederatedRayCluster{} },
			func() *rayv1.FederatedRayClusterList { return &rayv1.FederatedRayClusterList{} },
		),
	}
}
