// Code generated by client-gen. DO NOT EDIT.

package v1

type FederatedRayClusterExpansion interface{}

type RayClusterExpansion interface{}

type RayCronJobExpansion interface{}

type RayJobExpansion interface{}

type RayServiceExpansion interface{}
