// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	rayv1 "github.com/ray-project/kuberay/ray-operator/apis/ray/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// FederatedRayClusterLister helps list FederatedRayClusters.
// All objects returned here must be treated as read-only.
type FederatedRayClusterLister interface {
	// List lists all FederatedRayClusters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*rayv1.FederatedRayCluster, err error)
	// FederatedRayClusters returns an object that can list and get FederatedRayClusters.
	FederatedRayClusters(namespace string) FederatedRayClusterNamespaceLister
	FederatedRayClusterListerExpansion
}

// federatedRayClusterLister implements the FederatedRayClusterLister interface.
type federatedRayClusterLister struct {
	listers.ResourceIndexer[*rayv1.FederatedRayCluster]
}

// NewFederatedRayClusterLister returns a new FederatedRayClusterLister.
func NewFederatedRayClusterLister(indexer cache.Indexer) FederatedRayClusterLister {
	return &federatedRayClusterLister{listers.New[*rayv1.FederatedRayCluster](indexer, rayv1.Resource("federatedraycluster"))}
}

// FederatedRayClusters returns an object that can list and get FederatedRayClusters.
func (s *federatedRayClusterLister) FederatedRayClusters(namespace string) FederatedRayClusterNamespaceLister {
	return federatedRayClusterNamespaceLister{listers.NewNamespaced[*rayv1.FederatedRayCluster](s.ResourceIndexer, namespace)}
}

// FederatedRayClusterNamespaceLister helps list and get FederatedRayClusters.
// All objects returned here must be treated as read-only.
type FederatedRayClusterNamespaceLister interface {
	// List lists all FederatedRayClusters in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*rayv1.FederatedRayCluster, err error)
	// Get retrieves the FederatedRayCluster from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*rayv1.FederatedRayCluster, error)
	FederatedRayClusterNamespaceListerExpansion
}

// federatedRayClusterNamespaceLister implements the FederatedRayClusterNamespaceLister
// interface.
type federatedRayClusterNamespaceLister struct {
	listers.ResourceIndexer[*rayv1.FederatedRayCluster]
}
