// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// FederationWorkerGroupStatusApplyConfiguration represents a declarative configuration of the FederationWorkerGroupStatus type for use
// with apply.
//
// FederationWorkerGroupStatus is an aggregate observation, never a remote Pod inventory.
type FederationWorkerGroupStatusApplyConfiguration struct {
	GroupName          *string `json:"groupName,omitempty"`
	DesiredReplicas    *int32  `json:"desiredReplicas,omitempty"`
	ObservedReplicas   *int32  `json:"observedReplicas,omitempty"`
	ReadyReplicas      *int32  `json:"readyReplicas,omitempty"`
	PendingReplicas    *int32  `json:"pendingReplicas,omitempty"`
	FailedReplicas     *int32  `json:"failedReplicas,omitempty"`
	ObservedGeneration *int64  `json:"observedGeneration,omitempty"`
}

// FederationWorkerGroupStatusApplyConfiguration constructs a declarative configuration of the FederationWorkerGroupStatus type for use with
// apply.
func FederationWorkerGroupStatus() *FederationWorkerGroupStatusApplyConfiguration {
	return &FederationWorkerGroupStatusApplyConfiguration{}
}

// WithGroupName sets the GroupName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GroupName field is set to the value of the last call.
func (b *FederationWorkerGroupStatusApplyConfiguration) WithGroupName(value string) *FederationWorkerGroupStatusApplyConfiguration {
	b.GroupName = &value
	return b
}

// WithDesiredReplicas sets the DesiredReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DesiredReplicas field is set to the value of the last call.
func (b *FederationWorkerGroupStatusApplyConfiguration) WithDesiredReplicas(value int32) *FederationWorkerGroupStatusApplyConfiguration {
	b.DesiredReplicas = &value
	return b
}

// WithObservedReplicas sets the ObservedReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedReplicas field is set to the value of the last call.
func (b *FederationWorkerGroupStatusApplyConfiguration) WithObservedReplicas(value int32) *FederationWorkerGroupStatusApplyConfiguration {
	b.ObservedReplicas = &value
	return b
}

// WithReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyReplicas field is set to the value of the last call.
func (b *FederationWorkerGroupStatusApplyConfiguration) WithReadyReplicas(value int32) *FederationWorkerGroupStatusApplyConfiguration {
	b.ReadyReplicas = &value
	return b
}

// WithPendingReplicas sets the PendingReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PendingReplicas field is set to the value of the last call.
func (b *FederationWorkerGroupStatusApplyConfiguration) WithPendingReplicas(value int32) *FederationWorkerGroupStatusApplyConfiguration {
	b.PendingReplicas = &value
	return b
}

// WithFailedReplicas sets the FailedReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedReplicas field is set to the value of the last call.
func (b *FederationWorkerGroupStatusApplyConfiguration) WithFailedReplicas(value int32) *FederationWorkerGroupStatusApplyConfiguration {
	b.FailedReplicas = &value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *FederationWorkerGroupStatusApplyConfiguration) WithObservedGeneration(value int64) *FederationWorkerGroupStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
