// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	applyconfigurationsmetav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// FederationMemberStatusApplyConfiguration represents a declarative configuration of the FederationMemberStatus type for use
// with apply.
//
// FederationMemberStatus retains managed cleanup destinations before any remote write.
// Manual members have no credential or observable remote capacity.
type FederationMemberStatusApplyConfiguration struct {
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	// RayClusterName is the managed member's actual RayCluster name, persisted
	// before remote writes. Existing members retain their original names.
	// Manual members do not have a controller-assigned RayCluster name.
	RayClusterName *string `json:"rayClusterName,omitempty"`
	// RayClusterUID records the last child observed with this federation's ownership.
	// It distinguishes a failed create from a later change of ownership.
	RayClusterUID *types.UID `json:"rayClusterUID,omitempty"`
	// ClusterUID is the member API's kube-system namespace UID, persisted before
	// remote writes. Credential rotation must preserve this identity, including
	// during cleanup; a Secret name or API server URL is not a cluster identity.
	ClusterUID          *types.UID                                              `json:"clusterUID,omitempty"`
	KubeconfigSecretRef *corev1.LocalObjectReference                            `json:"kubeconfigSecretRef,omitempty"`
	ObservedGeneration  *int64                                                  `json:"observedGeneration,omitempty"`
	LastUpdateTime      *metav1.Time                                            `json:"lastUpdateTime,omitempty"`
	Conditions          []applyconfigurationsmetav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	WorkerGroupStatuses []FederationWorkerGroupStatusApplyConfiguration         `json:"workerGroupStatuses,omitempty"`
}

// FederationMemberStatusApplyConfiguration constructs a declarative configuration of the FederationMemberStatus type for use with
// apply.
func FederationMemberStatus() *FederationMemberStatusApplyConfiguration {
	return &FederationMemberStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *FederationMemberStatusApplyConfiguration) WithName(value string) *FederationMemberStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *FederationMemberStatusApplyConfiguration) WithNamespace(value string) *FederationMemberStatusApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithRayClusterName sets the RayClusterName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RayClusterName field is set to the value of the last call.
func (b *FederationMemberStatusApplyConfiguration) WithRayClusterName(value string) *FederationMemberStatusApplyConfiguration {
	b.RayClusterName = &value
	return b
}

// WithRayClusterUID sets the RayClusterUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RayClusterUID field is set to the value of the last call.
func (b *FederationMemberStatusApplyConfiguration) WithRayClusterUID(value types.UID) *FederationMemberStatusApplyConfiguration {
	b.RayClusterUID = &value
	return b
}

// WithClusterUID sets the ClusterUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterUID field is set to the value of the last call.
func (b *FederationMemberStatusApplyConfiguration) WithClusterUID(value types.UID) *FederationMemberStatusApplyConfiguration {
	b.ClusterUID = &value
	return b
}

// WithKubeconfigSecretRef sets the KubeconfigSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubeconfigSecretRef field is set to the value of the last call.
func (b *FederationMemberStatusApplyConfiguration) WithKubeconfigSecretRef(value corev1.LocalObjectReference) *FederationMemberStatusApplyConfiguration {
	b.KubeconfigSecretRef = &value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *FederationMemberStatusApplyConfiguration) WithObservedGeneration(value int64) *FederationMemberStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithLastUpdateTime sets the LastUpdateTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastUpdateTime field is set to the value of the last call.
func (b *FederationMemberStatusApplyConfiguration) WithLastUpdateTime(value metav1.Time) *FederationMemberStatusApplyConfiguration {
	b.LastUpdateTime = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *FederationMemberStatusApplyConfiguration) WithConditions(values ...*applyconfigurationsmetav1.ConditionApplyConfiguration) *FederationMemberStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithWorkerGroupStatuses adds the given value to the WorkerGroupStatuses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the WorkerGroupStatuses field.
func (b *FederationMemberStatusApplyConfiguration) WithWorkerGroupStatuses(values ...*FederationWorkerGroupStatusApplyConfiguration) *FederationMemberStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithWorkerGroupStatuses")
		}
		b.WorkerGroupStatuses = append(b.WorkerGroupStatuses, *values[i])
	}
	return b
}
