// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// FederatedRayClusterSpecApplyConfiguration represents a declarative configuration of the FederatedRayClusterSpec type for use
// with apply.
//
// FederatedRayClusterSpec describes one Ray runtime across private Kubernetes networks.
type FederatedRayClusterSpecApplyConfiguration struct {
	PrimaryCluster *FederationPrimaryClusterApplyConfiguration `json:"primaryCluster,omitempty"`
	MemberClusters []FederationMemberClusterApplyConfiguration `json:"memberClusters,omitempty"`
	Networking     *FederationNetworkingApplyConfiguration     `json:"networking,omitempty"`
	// Delete waits for remote cleanup. Orphan explicitly releases remote resources.
	MemberCleanupPolicy *string `json:"memberCleanupPolicy,omitempty"`
}

// FederatedRayClusterSpecApplyConfiguration constructs a declarative configuration of the FederatedRayClusterSpec type for use with
// apply.
func FederatedRayClusterSpec() *FederatedRayClusterSpecApplyConfiguration {
	return &FederatedRayClusterSpecApplyConfiguration{}
}

// WithPrimaryCluster sets the PrimaryCluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrimaryCluster field is set to the value of the last call.
func (b *FederatedRayClusterSpecApplyConfiguration) WithPrimaryCluster(value *FederationPrimaryClusterApplyConfiguration) *FederatedRayClusterSpecApplyConfiguration {
	b.PrimaryCluster = value
	return b
}

// WithMemberClusters adds the given value to the MemberClusters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MemberClusters field.
func (b *FederatedRayClusterSpecApplyConfiguration) WithMemberClusters(values ...*FederationMemberClusterApplyConfiguration) *FederatedRayClusterSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMemberClusters")
		}
		b.MemberClusters = append(b.MemberClusters, *values[i])
	}
	return b
}

// WithNetworking sets the Networking field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Networking field is set to the value of the last call.
func (b *FederatedRayClusterSpecApplyConfiguration) WithNetworking(value *FederationNetworkingApplyConfiguration) *FederatedRayClusterSpecApplyConfiguration {
	b.Networking = value
	return b
}

// WithMemberCleanupPolicy sets the MemberCleanupPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MemberCleanupPolicy field is set to the value of the last call.
func (b *FederatedRayClusterSpecApplyConfiguration) WithMemberCleanupPolicy(value string) *FederatedRayClusterSpecApplyConfiguration {
	b.MemberCleanupPolicy = &value
	return b
}
