// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// FederationHeadEndpointApplyConfiguration represents a declarative configuration of the FederationHeadEndpoint type for use
// with apply.
//
// FederationHeadEndpoint is a platform-managed stable private GCS endpoint.
type FederationHeadEndpointApplyConfiguration struct {
	// Only UserProvided is initially supported; networking is externally managed.
	Mode *string `json:"mode,omitempty"`
	// Private IP address or DNS name, without a scheme or port.
	Address *string `json:"address,omitempty"`
	GCSPort *int32  `json:"gcsPort,omitempty"`
}

// FederationHeadEndpointApplyConfiguration constructs a declarative configuration of the FederationHeadEndpoint type for use with
// apply.
func FederationHeadEndpoint() *FederationHeadEndpointApplyConfiguration {
	return &FederationHeadEndpointApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *FederationHeadEndpointApplyConfiguration) WithMode(value string) *FederationHeadEndpointApplyConfiguration {
	b.Mode = &value
	return b
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *FederationHeadEndpointApplyConfiguration) WithAddress(value string) *FederationHeadEndpointApplyConfiguration {
	b.Address = &value
	return b
}

// WithGCSPort sets the GCSPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GCSPort field is set to the value of the last call.
func (b *FederationHeadEndpointApplyConfiguration) WithGCSPort(value int32) *FederationHeadEndpointApplyConfiguration {
	b.GCSPort = &value
	return b
}
