// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
)

// FederationMemberClusterApplyConfiguration represents a declarative configuration of the FederationMemberCluster type for use
// with apply.
//
// FederationMemberCluster selects an existing remote namespace and optional credential.
type FederationMemberClusterApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
	// The Secret must be in the FRC namespace, labeled ray.io/federation-credential=true,
	// and contain a self-contained kubeconfig in data.kubeconfig.
	// Omit to manage the member manually. The federation never accesses that member API.
	KubeconfigSecretRef *corev1.LocalObjectReference `json:"kubeconfigSecretRef,omitempty"`
	Namespace           *string                      `json:"namespace,omitempty"`
	// Replicas and scaleStrategy initialize new managed groups; the primary
	// RayCluster owns their runtime targets after creation.
	// Targets are projected through the primary RayCluster to this managed member.
	WorkerGroups []WorkerGroupSpecApplyConfiguration `json:"workerGroups,omitempty"`
}

// FederationMemberClusterApplyConfiguration constructs a declarative configuration of the FederationMemberCluster type for use with
// apply.
func FederationMemberCluster() *FederationMemberClusterApplyConfiguration {
	return &FederationMemberClusterApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *FederationMemberClusterApplyConfiguration) WithName(value string) *FederationMemberClusterApplyConfiguration {
	b.Name = &value
	return b
}

// WithKubeconfigSecretRef sets the KubeconfigSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubeconfigSecretRef field is set to the value of the last call.
func (b *FederationMemberClusterApplyConfiguration) WithKubeconfigSecretRef(value corev1.LocalObjectReference) *FederationMemberClusterApplyConfiguration {
	b.KubeconfigSecretRef = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *FederationMemberClusterApplyConfiguration) WithNamespace(value string) *FederationMemberClusterApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithWorkerGroups adds the given value to the WorkerGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the WorkerGroups field.
func (b *FederationMemberClusterApplyConfiguration) WithWorkerGroups(values ...*WorkerGroupSpecApplyConfiguration) *FederationMemberClusterApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithWorkerGroups")
		}
		b.WorkerGroups = append(b.WorkerGroups, *values[i])
	}
	return b
}
