// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// FederatedRayClusterStatusApplyConfiguration represents a declarative configuration of the FederatedRayClusterStatus type for use
// with apply.
type FederatedRayClusterStatusApplyConfiguration struct {
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// User-provided endpoint published once the primary head is ready.
	// This reports primary head readiness, not cross-cluster reachability.
	HeadEndpoint          *FederationHeadEndpointApplyConfiguration  `json:"headEndpoint,omitempty"`
	Conditions            []metav1.ConditionApplyConfiguration       `json:"conditions,omitempty"`
	MemberClusterStatuses []FederationMemberStatusApplyConfiguration `json:"memberClusterStatuses,omitempty"`
}

// FederatedRayClusterStatusApplyConfiguration constructs a declarative configuration of the FederatedRayClusterStatus type for use with
// apply.
func FederatedRayClusterStatus() *FederatedRayClusterStatusApplyConfiguration {
	return &FederatedRayClusterStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *FederatedRayClusterStatusApplyConfiguration) WithObservedGeneration(value int64) *FederatedRayClusterStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithHeadEndpoint sets the HeadEndpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HeadEndpoint field is set to the value of the last call.
func (b *FederatedRayClusterStatusApplyConfiguration) WithHeadEndpoint(value *FederationHeadEndpointApplyConfiguration) *FederatedRayClusterStatusApplyConfiguration {
	b.HeadEndpoint = value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *FederatedRayClusterStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *FederatedRayClusterStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithMemberClusterStatuses adds the given value to the MemberClusterStatuses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MemberClusterStatuses field.
func (b *FederatedRayClusterStatusApplyConfiguration) WithMemberClusterStatuses(values ...*FederationMemberStatusApplyConfiguration) *FederatedRayClusterStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMemberClusterStatuses")
		}
		b.MemberClusterStatuses = append(b.MemberClusterStatuses, *values[i])
	}
	return b
}
