// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// FederationPrimaryClusterApplyConfiguration represents a declarative configuration of the FederationPrimaryCluster type for use
// with apply.
//
// FederationPrimaryCluster configures the primary head, local workers, and the
// single autoscaler running on that head for all managed worker groups.
type FederationPrimaryClusterApplyConfiguration struct {
	HeadGroupSpec *HeadGroupSpecApplyConfiguration `json:"headGroupSpec,omitempty"`
	RayVersion    *string                          `json:"rayVersion,omitempty"`
	// EnableInTreeAutoscaling runs one global autoscaler on the primary head.
	// Federation autoscaling currently requires Ray 2.56.0, autoscaler v2, and
	// kubeconfig credentials for every member.
	EnableInTreeAutoscaling *bool `json:"enableInTreeAutoscaling,omitempty"`
	// AutoscalerOptions configures the global autoscaler. The federation supplies
	// its command and args; version must be omitted or v2.
	AutoscalerOptions *AutoscalerOptionsApplyConfiguration `json:"autoscalerOptions,omitempty"`
	// Replicas and scaleStrategy initialize new groups. Existing groups keep
	// their runtime targets in the primary RayCluster in both scaling modes.
	WorkerGroups []WorkerGroupSpecApplyConfiguration `json:"workerGroups,omitempty"`
}

// FederationPrimaryClusterApplyConfiguration constructs a declarative configuration of the FederationPrimaryCluster type for use with
// apply.
func FederationPrimaryCluster() *FederationPrimaryClusterApplyConfiguration {
	return &FederationPrimaryClusterApplyConfiguration{}
}

// WithHeadGroupSpec sets the HeadGroupSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HeadGroupSpec field is set to the value of the last call.
func (b *FederationPrimaryClusterApplyConfiguration) WithHeadGroupSpec(value *HeadGroupSpecApplyConfiguration) *FederationPrimaryClusterApplyConfiguration {
	b.HeadGroupSpec = value
	return b
}

// WithRayVersion sets the RayVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RayVersion field is set to the value of the last call.
func (b *FederationPrimaryClusterApplyConfiguration) WithRayVersion(value string) *FederationPrimaryClusterApplyConfiguration {
	b.RayVersion = &value
	return b
}

// WithEnableInTreeAutoscaling sets the EnableInTreeAutoscaling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableInTreeAutoscaling field is set to the value of the last call.
func (b *FederationPrimaryClusterApplyConfiguration) WithEnableInTreeAutoscaling(value bool) *FederationPrimaryClusterApplyConfiguration {
	b.EnableInTreeAutoscaling = &value
	return b
}

// WithAutoscalerOptions sets the AutoscalerOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoscalerOptions field is set to the value of the last call.
func (b *FederationPrimaryClusterApplyConfiguration) WithAutoscalerOptions(value *AutoscalerOptionsApplyConfiguration) *FederationPrimaryClusterApplyConfiguration {
	b.AutoscalerOptions = value
	return b
}

// WithWorkerGroups adds the given value to the WorkerGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the WorkerGroups field.
func (b *FederationPrimaryClusterApplyConfiguration) WithWorkerGroups(values ...*WorkerGroupSpecApplyConfiguration) *FederationPrimaryClusterApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithWorkerGroups")
		}
		b.WorkerGroups = append(b.WorkerGroups, *values[i])
	}
	return b
}
