// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// FederationNetworkingApplyConfiguration represents a declarative configuration of the FederationNetworking type for use
// with apply.
//
// FederationNetworking identifies the platform-managed head endpoint.
// Cross-cluster network connectivity is a platform prerequisite.
type FederationNetworkingApplyConfiguration struct {
	HeadEndpoint *FederationHeadEndpointApplyConfiguration `json:"headEndpoint,omitempty"`
}

// FederationNetworkingApplyConfiguration constructs a declarative configuration of the FederationNetworking type for use with
// apply.
func FederationNetworking() *FederationNetworkingApplyConfiguration {
	return &FederationNetworkingApplyConfiguration{}
}

// WithHeadEndpoint sets the HeadEndpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HeadEndpoint field is set to the value of the last call.
func (b *FederationNetworkingApplyConfiguration) WithHeadEndpoint(value *FederationHeadEndpointApplyConfiguration) *FederationNetworkingApplyConfiguration {
	b.HeadEndpoint = value
	return b
}
