// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apisrayv1 "github.com/ray-project/kuberay/ray-operator/apis/ray/v1"
	versioned "github.com/ray-project/kuberay/ray-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/ray-project/kuberay/ray-operator/pkg/client/informers/externalversions/internalinterfaces"
	rayv1 "github.com/ray-project/kuberay/ray-operator/pkg/client/listers/ray/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// FederatedRayClusterInformer provides access to a shared informer and lister for
// FederatedRayClusters. Prefer using the type-safe variant (see [TypedFederatedRayClusterInformer]).
type FederatedRayClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() rayv1.FederatedRayClusterLister
}

// TypedFederatedRayClusterInformer provides access to a shared informer and lister for
// FederatedRayClusters, including the type-safe TypedInformer variant.
// It is a superset of FederatedRayClusterInformer.
type TypedFederatedRayClusterInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() FederatedRayClusterIndexInformer
	Lister() rayv1.FederatedRayClusterLister
}

// FederatedRayClusterIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type FederatedRayClusterIndexInformer cache.TypedSharedIndexInformer[*apisrayv1.FederatedRayCluster]

// FederatedRayClusterHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for FederatedRayCluster.
type FederatedRayClusterHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apisrayv1.FederatedRayCluster]

// FederatedRayClusterDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for FederatedRayCluster.
type FederatedRayClusterDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apisrayv1.FederatedRayCluster]

// FederatedRayClusterFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for FederatedRayCluster.
type FederatedRayClusterFilteringHandler = cache.TypedFilteringResourceEventHandler[*apisrayv1.FederatedRayCluster]

// FederatedRayClusterIndexers is a specialization of [cache.TypedIndexers] for FederatedRayCluster.
type FederatedRayClusterIndexers = cache.TypedIndexers[*apisrayv1.FederatedRayCluster]

// DeletedFederatedRayCluster is a specialization of [cache.DeletedObject] for FederatedRayCluster.
type DeletedFederatedRayCluster = cache.DeletedObject[*apisrayv1.FederatedRayCluster]

type federatedRayClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewFederatedRayClusterInformer constructs a new informer for FederatedRayCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFederatedRayClusterInformer]).
func NewFederatedRayClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFederatedRayClusterInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedFederatedRayClusterInformer constructs a new informer for FederatedRayCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFederatedRayClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers FederatedRayClusterIndexers) FederatedRayClusterIndexInformer {
	return NewTypedFederatedRayClusterInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredFederatedRayClusterInformer constructs a new informer for FederatedRayCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredFederatedRayClusterInformer]).
func NewFilteredFederatedRayClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedFederatedRayClusterInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredFederatedRayClusterInformer constructs a new informer for FederatedRayCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredFederatedRayClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers FederatedRayClusterIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) FederatedRayClusterIndexInformer {
	return NewTypedFederatedRayClusterInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewFederatedRayClusterInformerWithOptions constructs a new informer for FederatedRayCluster type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFederatedRayClusterInformerWithOptions]).
func NewFederatedRayClusterInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedFederatedRayClusterInformerWithOptions(client, namespace, options)
}

// NewTypedFederatedRayClusterInformerWithOptions constructs a new informer for FederatedRayCluster type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFederatedRayClusterInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) FederatedRayClusterIndexInformer {
	gvr := schema.GroupVersionResource{Group: "ray.io", Version: "v1", Resource: "federatedrayclusters"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apisrayv1.FederatedRayCluster](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.RayV1().FederatedRayClusters(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.RayV1().FederatedRayClusters(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.RayV1().FederatedRayClusters(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.RayV1().FederatedRayClusters(namespace).Watch(ctx, opts)
			},
		}, client),
		&apisrayv1.FederatedRayCluster{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *federatedRayClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedFederatedRayClusterInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *federatedRayClusterInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *federatedRayClusterInformer) TypedInformer() FederatedRayClusterIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisrayv1.FederatedRayCluster](f.factory.InformerFor(&apisrayv1.FederatedRayCluster{}, f.defaultInformer))
}

func (f *federatedRayClusterInformer) Lister() rayv1.FederatedRayClusterLister {
	return rayv1.NewFederatedRayClusterLister(f.Informer().GetIndexer())
}

// ToTypedFederatedRayClusterInformer converts an untyped informer into a TypedFederatedRayClusterInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *FederatedRayCluster. If that is not the case, calling type-safe methods of the returned
// TypedFederatedRayClusterInformer leads to runtime panics. A safer alternative is to pass
// around a TypedFederatedRayClusterInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedFederatedRayClusterInformer(informer FederatedRayClusterInformer) TypedFederatedRayClusterInformer {
	if informer, ok := informer.(TypedFederatedRayClusterInformer); ok {
		return informer
	}
	return &federatedRayClusterTypedInformerAdapter{informer}
}

type federatedRayClusterTypedInformerAdapter struct {
	FederatedRayClusterInformer
}

func (a *federatedRayClusterTypedInformerAdapter) TypedInformer() FederatedRayClusterIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisrayv1.FederatedRayCluster](a.Informer())
}

// ToFederatedRayClusterIndexInformer converts an untyped informer into a FederatedRayClusterIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *FederatedRayCluster. If that is not the case, calling type-safe methods of the returned
// FederatedRayClusterIndexInformer leads to runtime panics. A safer alternative is to pass
// around a FederatedRayClusterIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToFederatedRayClusterIndexInformer(informer cache.SharedIndexInformer) FederatedRayClusterIndexInformer {
	if informer, ok := informer.(FederatedRayClusterIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apisrayv1.FederatedRayCluster](informer)
}
