// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/ray-project/kuberay/ray-operator/apis/ray/v1"
	rayv1 "github.com/ray-project/kuberay/ray-operator/pkg/client/applyconfiguration/ray/v1"
	typedrayv1 "github.com/ray-project/kuberay/ray-operator/pkg/client/clientset/versioned/typed/ray/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeFederatedRayClusters implements FederatedRayClusterInterface
type fakeFederatedRayClusters struct {
	*gentype.FakeClientWithListAndApply[*v1.FederatedRayCluster, *v1.FederatedRayClusterList, *rayv1.FederatedRayClusterApplyConfiguration]
	Fake *FakeRayV1
}

func newFakeFederatedRayClusters(fake *FakeRayV1, namespace string) typedrayv1.FederatedRayClusterInterface {
	return &fakeFederatedRayClusters{
		gentype.NewFakeClientWithListAndApply[*v1.FederatedRayCluster, *v1.FederatedRayClusterList, *rayv1.FederatedRayClusterApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("federatedrayclusters"),
			v1.SchemeGroupVersion.WithKind("FederatedRayCluster"),
			func() *v1.FederatedRayCluster { return &v1.FederatedRayCluster{} },
			func() *v1.FederatedRayClusterList { return &v1.FederatedRayClusterList{} },
			func(dst, src *v1.FederatedRayClusterList) { dst.ListMeta = src.ListMeta },
			func(list *v1.FederatedRayClusterList) []*v1.FederatedRayCluster {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.FederatedRayClusterList, items []*v1.FederatedRayCluster) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
